In [4]:
using LinearAlgebra, Plots

#  [Atividade Computacional 1](http://mtm.ufsc.br/~douglas/2025.1/MTM410024_MTM3523/Atividade1.pdf)


## Questão 1

> Calcular o número de condição da matriz de Hilbert de tamanho 10, 100 e 1000.

A fórmula para o elemento $(i,j)$ é $$\frac{1}{i+j-1}$$

Criando a matriz de Hilbert:

In [5]:
function MatrixHilbert(n)
  A = zeros(n,n)
  for i = 1:n
    for j = 1:n
      A[i,j] = 1/(i+j-1)
    end
  end
      A
end;

In [6]:
H10 = MatrixHilbert(10)
H100 = MatrixHilbert(100)
H1000 = MatrixHilbert(1000);

Vamos usar a função `cond` do `julia`

In [8]:
cond(H10)

1.602441698742836e13

In [ ]:
cond(H100)

3.0310502811585376e19

In [ ]:
cond(H1000)

3.956047868337803e21

## Questão 2

Resolver o sistema $$Ax = A_{[:,end]}$$

In [9]:
# H10 já está definida
H20 = MatrixHilbert(20)
H40 = MatrixHilbert(40);

Vamos criar uma função auxiliar que produz os vetores solução


In [10]:
xsolucao(n) = begin
  v = zeros(n)
  v[n] = 1
  v
end

xsolucao (generic function with 1 method)

Vamos criar os vetores solução para comparar com as soluções encontradas


In [11]:
xs10 = xsolucao(10)
xs20 = xsolucao(20)
xs40 = xsolucao(40);

Vamos resolver o sistema usando o famoso operador `backslash`


In [12]:
x10 = H10\H10[:,end]
x20 = H20\H20[:,end]
x40 = H40\H40[:,end];

Comparando as soluções encontradas

In [13]:
errorelativo(x0, x) = norm(x0-x)/norm(x)

errorelativo (generic function with 1 method)

In [14]:
errorelativo(x10, xs10)

8.82004958406119e-5

In [15]:
errorelativo(x20, xs20)

17.479329722835804

In [16]:
errorelativo(x40, xs40)

18.75699831471733

Note que o erro relativo até que está controlado no caso $n=10$, mas explode
em $n=20$ e $n=40$

## Questão 3

In [17]:
A = [ 1 1; 1 1.0001]
b = [2 ; 2];

In [18]:
cond(A)

40002.00007491187

In [19]:
x = A\b

2-element Vector{Float64}:
 2.0
 0.0

In [20]:
δb = [0; 0.0001];

In [21]:
xδx = A\(b+δb)

2-element Vector{Float64}:
 0.9999999999977796
 1.0000000000022204

In [22]:
δx = x - xδx

2-element Vector{Float64}:
  1.0000000000022204
 -1.0000000000022204

In [23]:
norm(δx)/norm(x)

0.7071067811881177

In [24]:
norm(δb)/norm(b)*cond(A)

1.4142842756997482

Veja que o erro relativo usa 50% da cota máxima de erro

## Questão 4

In [25]:
function substituicaoReversa(U,b)
  m,n = size(U)
  nb = length(b)
  if m != n
    throw( DimensionMismatch("Matriz U não é quadrada ($m x $n)"))
  end
  if nb != n
    throw(DimensionMismatch("Lado direito não tem o tamanho correto: U($m x $n), b($nb)"))
  end
  x = zeros(n)
  x[n] = b[n]/U[n,n]
  for i = n-1:-1:1
    x[i] = (b[i] - U[i,i:end]'*x[i:end])/U[i,i]
  end
  x
end

substituicaoReversa (generic function with 1 method)

In [26]:
A = [1 2; 0 4]
b = [1; 2]

2-element Vector{Int64}:
 1
 2

In [27]:
substituicaoReversa(A,b)

2-element Vector{Float64}:
 0.0
 0.5

In [ ]:
A

2×2 Matrix{Int64}:
 1  2
 0  4

In [ ]:
b

2-element Vector{Int64}:
 1
 2

In [31]:
n = 20
B = rand(n,n)
A = UpperTriangular(B);
b = A*ones(n);

In [32]:
x= substituicaoReversa(A,b)

20-element Vector{Float64}:
 0.999999999999727
 1.0000000000001723
 0.999999999999895
 1.0000000000007372
 0.9999999999997311
 1.0000000000000493
 1.0000000000001004
 0.9999999999998542
 1.0000000000000948
 0.999999999999892
 1.0000000000000338
 0.9999999999999774
 1.000000000000004
 0.9999999999999992
 0.9999999999999994
 1.0000000000000004
 1.0000000000000002
 0.9999999999999999
 1.0
 1.0

In [30]:
norm(A*x-b)/norm(b)

3.8531446186688754e-11