# Aula aplicada 01

## Noções de `julia`

In [ ]:
x = 3;
y = 3.14159;

In [ ]:
# @markdown Acessando tipos das variáveis
typeof(x), typeof(y)

(Int64, Float64)

In [ ]:
z = x + y

6.14159

In [ ]:
# @markdown Conversão automática de tipos
typeof(z)

Float64

In [ ]:
# @markdown Geração de vetores
u = [3, 3.42, -3]
v =  rand(3)
w = ones(3)
z = zeros(3)

3-element Vector{Float64}:
 0.0
 0.0
 0.0

In [ ]:
# @markdown Criação de matrizes
[u v w z]

3×4 Matrix{Float64}:
  3.0   0.390424  1.0  0.0
  3.42  0.573415  1.0  0.0
 -3.0   0.130994  1.0  0.0

In [ ]:
# @markdown Aplicações da função `rand`
rand(1:50, 2, 3)

2×3 Matrix{Int64}:
 16   2  34
 29  22  38

## Operações com vetores e acessando elementos

In [ ]:
u  + v

3-element Vector{Float64}:
  3.390424025466732
  3.9934145506332976
 -2.869006162851015

In [ ]:
u[1]

3.0

In [ ]:
3*u

3-element Vector{Float64}:
  9.0
 10.26
 -9.0

In [ ]:
u[2:3]

2-element Vector{Float64}:
  3.42
 -3.0

In [ ]:
v'w

1.0948324132490144

In [ ]:
v*w'

3×3 Matrix{Float64}:
 0.390424  0.390424  0.390424
 0.573415  0.573415  0.573415
 0.130994  0.130994  0.130994

In [ ]:
v*w'w

3-element Vector{Float64}:
 1.171272076400196
 1.7202436518998927
 0.3929815114469545

In [ ]:
# @markdown `u2` aponta para a mesma posição de memória de `u`
# @markdown
# @markdown alterações em um afetam o outro
u2 = u

3-element Vector{Float64}:
 3.0
 3.42
 2.3

In [ ]:
u[3] = 2.3

2.3

In [ ]:
# @markdown `u2` agora é uma cópia, e fica independente de `u`
u2 = copy(u)

3-element Vector{Float64}:
 3.0
 3.42
 2.3

In [ ]:
A  =[[1,2,3] [4,5,6] [7,8,0]]

3×3 Matrix{Int64}:
 1  4  7
 2  5  8
 3  6  0

In [ ]:
A  =[ 1 2 3; 4 5 6; 7 8 0]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  0

In [ ]:
B = ones(3,3)

3×3 Matrix{Float64}:
 1.0  1.0  1.0
 1.0  1.0  1.0
 1.0  1.0  1.0

In [ ]:
A[1:2,2:end]

2×2 Matrix{Int64}:
 2  3
 5  6

In [ ]:
4*I(4)

4×4 Diagonal{Int64, Vector{Int64}}:
 4  ⋅  ⋅  ⋅
 ⋅  4  ⋅  ⋅
 ⋅  ⋅  4  ⋅
 ⋅  ⋅  ⋅  4

In [ ]:
A*u

3-element Vector{Float64}:
 16.74
 42.9
 48.36

In [ ]:
u'A

1×3 adjoint(::Vector{Float64}) with eltype Float64:
 32.78  41.5  29.52

In [ ]:
Asym = A + A'

3×3 Matrix{Int64}:
  2   6  10
  6  10  14
 10  14   0

In [ ]:
typeof(Asym)

Matrix{Int64} (alias for Array{Int64, 2})

In [ ]:
norm(A,2)

14.2828568570857

In [ ]:
norm(Asym - Asym')

0.0

In [ ]:
opnorm(A,1)

15.0

In [ ]:
# o fruto proibido
# comando backslash \: matriz left division

A\w


3-element Vector{Float64}:
 -1.0000000000000002
  1.0000000000000002
 -3.7007434154171895e-17

In [ ]:
A*[-1,1,0]

3-element Vector{Int64}:
 1
 1
 1

In [ ]:
A\[1,1,1]

3-element Vector{Float64}:
 -1.0000000000000002
  1.0000000000000002
 -3.7007434154171895e-17

In [ ]:
?\

search: \



```
\(x, y)
```

Left division operator: multiplication of `y` by the inverse of `x` on the left. Gives floating-point results for integer arguments.

# Examples

```jldoctest
julia> 3 \ 6
2.0

julia> inv(3) * 6
2.0

julia> A = [4 3; 2 1]; x = [5, 6];

julia> A \ x
2-element Vector{Float64}:
  6.5
 -7.0

julia> inv(A) * x
2-element Vector{Float64}:
  6.5
 -7.0
```

---

```
\(A, B)
```

Matrix division using a polyalgorithm. For input matrices `A` and `B`, the result `X` is such that `A*X == B` when `A` is square. The solver that is used depends upon the structure of `A`.  If `A` is upper or lower triangular (or diagonal), no factorization of `A` is required and the system is solved with either forward or backward substitution. For non-triangular square matrices, an LU factorization is used.

For rectangular `A` the result is the minimum-norm least squares solution computed by a pivoted QR factorization of `A` and a rank estimate of `A` based on the R factor.

When `A` is sparse, a similar polyalgorithm is used. For indefinite matrices, the `LDLt` factorization does not use pivoting during the numerical factorization and therefore the procedure can fail even for invertible matrices.

See also: [`factorize`](@ref), [`pinv`](@ref).

# Examples

```jldoctest
julia> A = [1 0; 1 -2]; B = [32; -4];

julia> X = A \ B
2-element Vector{Float64}:
 32.0
 18.0

julia> A * X == B
true
```


In [ ]:
B = [[3,0,0] [4,2,0] [-1,1,6]]

3×3 Matrix{Int64}:
 3  4  -1
 0  2   1
 0  0   6

In [ ]:
B*ones(3)

3-element Vector{Float64}:
 6.0
 3.0
 6.0

In [ ]:
B\[6,3,6]

3-element Vector{Float64}:
 1.0
 1.0
 1.0

## Sistema sobredeterminado

In [ ]:
C = [1 0; 0 0; 0 0 ]
b = [2, 3, -1]

3-element Vector{Int64}:
  2
  3
 -1

In [ ]:
x = C\b

2-element Vector{Float64}:
 2.0
 0.0

In [ ]:
norm(C*x -b)

3.1622776601683795

In [ ]:
C'C

2×2 Matrix{Int64}:
 1  0
 0  0

In [ ]:
C'b

2-element Vector{Int64}:
 2
 0

In [ ]:
rank(C)

1

## Sistema subdeterminado

In [ ]:
D  = [ 1 0 3; 0 2 0]

2×3 Matrix{Int64}:
 1  0  3
 0  2  0

In [ ]:
xs  = [1,2,0]
b = D*xs

2-element Vector{Int64}:
 1
 4

In [ ]:
x= D\b

3-element Vector{Float64}:
 0.10000000000000002
 2.0
 0.3000000000000001

In [ ]:
norm(x), norm(xs)

(2.0248456731316584, 2.23606797749979)

In [ ]:
lu(A)

LU{Float64, Matrix{Float64}, Vector{Int64}}
L factor:
3×3 Matrix{Float64}:
 1.0       0.0  0.0
 0.142857  1.0  0.0
 0.571429  0.5  1.0
U factor:
3×3 Matrix{Float64}:
 7.0  8.0       0.0
 0.0  0.857143  3.0
 0.0  0.0       4.5

In [ ]:
qr(A)

LinearAlgebra.QRCompactWY{Float64, Matrix{Float64}, Matrix{Float64}}
Q factor: 3×3 LinearAlgebra.QRCompactWYQ{Float64, Matrix{Float64}, Matrix{Float64}}
R factor:
3×3 Matrix{Float64}:
 -8.12404  -9.60114   -3.32347
  0.0       0.904534   4.52267
  0.0       0.0       -3.67423

## Substituição direta


Dado um sistema triangular inferior $$Lx = b$$
Podemos calcular
$$x_1 = b_1/L_{11}$$
$$x_2 = (b_2 - L_{21}x_1 )/{L_{22}}$$

$$x_i = \left(b_i - \sum_{k=1}^{i-1}L_{ik}x_k\right)/L_{ii}$$

In [ ]:
f(x,y) = x^2 - y^2


f (generic function with 1 method)

In [ ]:
f(x::Vector, y::Vector) = x'x - y'y

f (generic function with 2 methods)

In [ ]:
f(A,B)

3×3 Matrix{Int64}:
 21  16  20
 66  77  34
 39  54  33

In [ ]:
u, v

([3.0, 3.42, 2.3], [0.39042402546673205, 0.5734145506332976, 0.13099383714898483])

In [ ]:
f.(u,v)

3-element Vector{Float64}:
  8.847569080338353
 11.367595753122012
  5.272840614628985

In [ ]:
A

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  0

In [ ]:
A[1,2:3]'*[1,-2]

-4

In [ ]:
size(A)

(3, 3)

In [ ]:
function substituicaoDireta2(L,b)
  m,n = size(L)
  x = zeros(n)
  x[1] = b[1]/L[1,1]
  for i = 2:n
    soma = 0
    for k = 1:i-1
      soma += L[i,k]*x[k]
    end
    x[i] = (b[i] - soma)/L[i,i]
  end
  x
end

substituicaoDireta2 (generic function with 1 method)

In [ ]:
function substituicaoDireta(L,b)
  m,n = size(L)
  x = zeros(n)
  x[1] = b[1]/L[1,1]
  for i = 2:n
    x[i] = (b[i] - L[i,1:i-1]'*x[1:i-1])/L[i,i]
  end
  x
end

substituicaoDireta (generic function with 1 method)

In [ ]:
function substituicaoReversa(U,b)
  m,n = size(U)
  x = zeros(n)
  x[n] = b[n]/U[n,n]
  for i = n-1:-1:1
    x[i] = (b[i] - U[i,i:end]'*x[i:end])/U[i,i]
  end
  x
end

substituicaoReversa (generic function with 1 method)

In [ ]:
x1 = [1,0,0]
x2 = [0,3,-1]
x3 = [0,0,10]

3-element Vector{Int64}:
  0
  0
 10

In [ ]:
substituicaoDireta(A',A'x1)

3-element Vector{Float64}:
 1.0
 0.0
 0.0

In [ ]:
substituicaoDireta(A',A'x2)

3-element Vector{Float64}:
  0.0
  3.0
 -1.0

In [ ]:
substituicaoDireta(A',A'x3)

3-element Vector{Float64}:
  0.0
  0.0
 10.0

In [ ]:
substituicaoReversa(A,A*x1), x1

([1.0, 0.0, 0.0], [1, 0, 0])

In [ ]:
substituicaoReversa(A,A*x2), x2

([0.0, 3.0, -1.0], [0, 3, -1])

In [ ]:
substituicaoReversa(A,A*x3), x3

([0.0, 0.0, 10.0], [0, 0, 10])

## Performance

In [ ]:
n = 10_000
A = rand(n,n)
L = tril(A)
xs = ones(n)
b = L*xs;

In [ ]:
@time x = substituicaoDireta(L,b);

  2.315034 seconds (35.90 k allocations: 764.676 MiB, 7.12% gc time)


In [ ]:
@time x = substituicaoDireta2(L,b);

  1.251314 seconds (2 allocations: 78.172 KiB)


In [ ]:
@time x = L\b;

  0.101217 seconds (2 allocations: 78.172 KiB)


In [ ]:
@time x  = inv(L)*b;

LoadError: InterruptException:

In [1]:
using LinearAlgebra

In [21]:
u = [1,2,3,4]
v = [1,1,-1,2];

In [22]:
A = u*v'

4×4 Matrix{Int64}:
 1  1  -1  2
 2  2  -2  4
 3  3  -3  6
 4  4  -4  8

In [23]:
norm(A,2)^2

209.99999999999997

In [24]:
opnorm(A,2)^2

209.99999999999994

In [28]:
u'v, v'v

(8, 7)

In [26]:
eigen(A'A)

Eigen{Float64, Float64, Matrix{Float64}, Vector{Float64}}
values:
4-element Vector{Float64}:
   0.0
   7.105427357600999e-15
   1.7053025658242404e-13
 210.0
vectors:
4×4 Matrix{Float64}:
  0.707107     -0.408248   0.436436   0.377964
 -0.707107     -0.408248   0.436436   0.377964
  3.14834e-17  -0.816497  -0.436436  -0.377964
  0.0           0.0       -0.654654   0.755929